---
title: "pip_EDA"
author: "Sifan"
date: "July 31, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(corrplot)
```


## Plot

Create quick bar plots to compare across peer groups

```{r, include=FALSE}
quick_bar = function(df, var,HL = "0",wt = F, scale = 1, acc = 0.1){
  df <- df %>% 
    mutate_(value = var) %>%
    mutate(value = value*scale) %>%
    mutate(highlight = (cbsa_code == HL))
  
  if (wt) {df <- df %>% mutate(value = value/cbsa_emp)}
  
  ggplot(df,aes(x = reorder(cbsa_name,value), y = value, 
                label = scales::comma(value,acc), fill = highlight))+
  geom_bar(stat = "identity")+
  geom_text()+
  scale_fill_discrete(guide = F)+
  coord_flip()+
  ggtitle(var)
  
  # return(df)
}



```


<font color = "red">[CHANGE INPUTS HERE]</font>

```{r plot, echo = FALSE}
quick_bar(cbsa_output, "rd_total",HL ="13820",wt = T)
# quick_bar(cbsa_output, "biz_rd", HL ="13820",wt = T,scale = 1000)

quick_bar(cbsa_output, "patents_issued", wt = T, scale = 1000)
quick_bar(cbsa_output, "patent_complexity",HL ="13820")

quick_bar(cbsa_output, "i5hgc_density",HL ="13820")
quick_bar(cbsa_output, "employment_at_firms_0_5_years_old", wt = T, acc = 0.01)

quick_bar(cbsa_output, "movein_pct_ba_above",acc = 0.01, HL ="13820")
quick_bar(cbsa_output, "pct_movein",acc = 0.01, HL ="13820")

```



### Create correlation matrix
```{r corrplot}

cbsa_cor <- cbsa_df %>% 
  select(-contains("from"),-year)%>%
  select_if(is.numeric)

M <- cor(cbsa_cor, use = "pairwise.complete.obs")

corrplot(M, method = "color", type ="upper",
         addCoef.col = "black", tl.col = "black",tl.srt=45)

```

